import fs from "fs";
import path from "path";
import consola from "consola";
import { inferSchemaFromEnv } from "../../core/inferSchema.js";
import { loadEnv } from "../../core/loader.js";

export function runGenerate(options: { env?: string; out?: string } = {}) {
  const envFile = options.env || ".env";
  const outFile = options.out || "env.d.ts";
  const resolvedEnv = path.resolve(process.cwd(), envFile);
  const resolvedOut = path.resolve(process.cwd(), outFile);

  if (!fs.existsSync(resolvedEnv)) {
    consola.error(`Environment file '${envFile}' not found.`);
    process.exit(1);
  }

  const rawEnv = loadEnv([resolvedEnv]);
  const schema = inferSchemaFromEnv(rawEnv);

  const lines: string[] = [
    "// Auto-generated by forgenv generate. Do not edit manually.",
    "declare namespace NodeJS {",
    "  interface ProcessEnv {",
  ];

  for (const key of Object.keys(schema)) {
    const field = schema[key];
    let tsType = "string";
    if (field && "type" in field && field.type === "number") tsType = "number";
    else if (field && "type" in field && field.type === "boolean") tsType = "boolean";

    lines.push(`    ${key}?: string;`);
  }

  lines.push("  }", "}", "");
  lines.push("export {};");

  fs.writeFileSync(resolvedOut, lines.join("\n"), "utf-8");
  consola.success(`Generated TypeScript type definitions in [${outFile}]`);
}
